#!/bin/bash

image=mesg/core:local
version="dev local"
env MESG_CORE_IMAGE=$image \
  go run \
  -ldflags="-X 'github.com/mesg-foundation/core/version.Version=$version'" \
  interface/cli/main.go \
  $@ 